#Location: .github/workflows/custom_config.yml
name: CI-CD pipeline to AWS
env:
  EB_S3_BUCKET_NAME: "behnam-ci-cd-bucket2"
  EB_APPLICATION_NAME: "djangoTest"
  EB_ENVIRONMENT_NAME: "Djangotest-env"
  DEPLOY_PACKAGE_NAME: "django-app-${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-2"

on:
  push:
    branches:
      - master #Use your own branch here (Might be staging or testing)



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install awsebcli --upgrade --user

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-2"


      - name: Initialize EB CLI
        run: eb init --platform python-3.8 "djangoTest"

      - name: Replace AWS Sample Application with Django server
        run: |
          eb use "Djangotest-env"
          eb deploy --staged --label "behnamLabel"
